apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: fraud-assessment-api
  annotations:
    scenarios.ai.sap.com/name: "fraud-detection-claims"
    scenarios.ai.sap.com/description: "Motor insurance fraud assessment API"
    executables.ai.sap.com/name: "fraud-assessment-api"
    executables.ai.sap.com/description: "Joule-friendly fraud assessment endpoint"
  labels:
    scenarios.ai.sap.com/id: "fraud-detection-claims"
    executables.ai.sap.com/id: "fraud-assessment-api"
    ai.sap.com/version: "1.0.7"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    kind: InferenceService
    metadata:
      name: fraud-assessment-api
      annotations: |
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: docker.io/itsmarlo/fraud-detection-claims-api:v1
            ports:
              - containerPort: 8080
